### PR TITLE
Escape special characters from string passed to RegExp

### LINKED ISSUE #132: Escape strings fed to RegExp to prevent crashes
Anywhere we're creating `RegExp` objects using user data we need to escape it to prevent invalid regular expressions that can throw errors.

For example searching for `*.*` create's an invalid regular expression, and throws an error, which will crash an app. _Please don't crash the demo._ 😉 

We should install [`escape-string-regexp`](https://www.npmjs.com/package/escape-string-regexp) and patch the following files:
- server/api/accounts.js 
- server/api/admin-groups.js 
- server/api/admins.js 
- server/api/statuses.js 
- server/api/users.js 

Example patch:

``` diff
const EscapeRegExp = require('escape-string-regexp');

// ...

if (request.query.pivot) {
-    query.pivot = new RegExp('^.*?' + request.query.pivot + '.*$', 'i');
+    query.pivot = new RegExp('^.*?' + EscapeRegExp(request.query.pivot) + '.*$', 'i');
}
```

### PR DESCRIPTION
**Pull request by ivanph**
Fixes #132

### CODE REVIEW

File: server/api/users.js [hunk 1]
```diff
@@ -22,7 +23,7 @@ internals.applyRoutes = function (server, next) {
             },
             validate: {
                 query: {
-                    username: Joi.string().token().lowercase().allow(''),
+                    username: Joi.string().lowercase().allow(''),
```
Comment (jedireza) [inline server/api/users.js]: let's remove the `lowercase()` too

File: server/api/accounts.js [hunk 2]
```diff
@@ -3,6 +3,7 @@ const Async = require('async');
 const AuthPlugin = require('../auth');
 const Boom = require('boom');
 const Joi = require('joi');
+const EscapeRegExp = require('escape-string-regexp');
```
Comment (jedireza) [inline server/api/accounts.js]: Let's order the requires alphabetically, `EscapeRegExp` coming before `Joi`.

File: test/server/api/accounts.js [hunk 3]
```diff
@@ -143,6 +143,27 @@ lab.experiment('Accounts Plugin Result List', () => {
             done();
         });
     });
+
```
Comment (jedireza) [inline test/server/api/accounts.js]: We can remove these tests. Since `pagedFind` is mocked (and we're not doing an integration test) we're not actually testing that special characters don't crash the app.

**Comment by ivanph** [comment]
Done. Let me know if there's any other changes needed.

**Comment by jedireza** [comment]
:shipit: thanks!
